name: Dummy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: wget
      run: wget https://google.com

  test2:

    runs-on: ubuntu-latest

    steps:
    - name: wget2
      run: wget https://google.de
